[book]
authors = ["Matthew Ballard"]
language = "en"
multilingual = false
src = "src"
title = "Derived Categories II"

# [preprocessor.latexy]
[preprocessor.mathenvirons]

[preprocessor.katex]

# [preprocessor.bib]
# bibliography = "748.bib"

[output.katex]
[output.html]
default-theme = "navy"
git-repository-url = "https://github.com/UofSC-Spring-2022-Math-748-001/jekyll.git"
git-repository-icon = "fa-github"

[output.html.fold]
enable = true
